# Generated by Django 3.2.5 on 2021-07-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210722_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisevent',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hisevent',
            name='remind_message',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hisevent',
            name='data_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='hisevent',
            name='remind',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'За час'), (2, 'За 2 часа'), (4, 'За 4 часа'), (24, 'За день'), (168, 'За неделю')], null=True),
        ),
    ]
