# Generated by Django 3.2.5 on 2021-08-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210729_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=70)),
                ('holidays', models.CharField(max_length=120)),
                ('datestartholiday', models.DateTimeField()),
                ('dateendholiday', models.DateTimeField()),
            ],
        ),
    ]
